---
title: "Data Visualization"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
    source_code: embed
runtime: shiny
---

```{r}
library(shiny)
library(flexdashboard)
library(ggplot2)
```

Probability Distribution Calculator
=======================================================================

Sidebar {.sidebar}
-------------------------------------

#### Distribution Parameters 

```{r}

selectInput("Type", label = "Select the Distribution Type",
            choices = c("Discrete", "Continuous",""), selected = "")

renderUI({
  switch (input$Type,
    "Discrete" = selectInput("Dist", label = "Select the Distribution", choices = c("Discrete Uniform","Bernoulli","Binomial","Negative Binomial","Poisson","Geometric", "Hyper-Geometric",""), selected = ""),
    "Continuous" = selectInput("Dist",label = "Select the Distribution", choices = c("Normal","Chi-Square","F","Student t","Gamma","Exponential","Beta","Uniform",""), selected = "")
  )
})

conditionalPanel("input.Dist=='Discrete Uniform'", numericInput("a", label = "a", value = 0, step = 1, min = -Inf, max = Inf), numericInput("b", label = "b", value = 1, step = 1, min = -Inf, max = Inf))

conditionalPanel("input.Dist=='Bernoulli' | input.Dist=='Geometric'", numericInput("p", label = "Enter the probability", value = 0.5, step = 0.1, min = 0, max = 1))

conditionalPanel("input.Dist=='Binomial' | input.Dist=='Negative Binomial'", numericInput("n", label = "Enter the number of Trials(n)", value = 0, step = 1, min = 1, max = Inf), numericInput("p", label = "Enter the probability", value = 0.5, step = 0.1, min = 0, max = 1))

conditionalPanel("input.Dist=='Poisson'", numericInput("lambda", label = "Enter the probability", value = 5, step = 1, min = 0, max = Inf))

conditionalPanel("input.Dist=='Hyper-Geometric'", numericInput("N", label = "N", value = 0, step = 1, min = 0, max = Inf), numericInput("n", label = "n", value = 1, step = 1, min = 0, max = Inf),numericInput("m", label = "m", value = 1, step = 1, min = 0, max = Inf))

conditionalPanel("input.Dist=='Normal'", numericInput("Mu", label = withMathJax(helpText("$$\\mu$$")), value = 0, step = 0.1, min = -Inf, max = Inf), numericInput("Sigma", label = withMathJax(helpText("$$\\sigma^2$$")), value = 1, step = 0.1, min = 0, max = Inf))

conditionalPanel("input.Dist=='F' | input.Dist=='Gamma' | input.Dist=='Beta'", numericInput("d1", label = withMathJax(helpText("$$\\mu$$")), value = 0, step = 0.1, min = -Inf, max = Inf), numericInput("d2", label = withMathJax(helpText("$$\\sigma^2$$")), value = 1, step = 0.1, min = 0, max = Inf))

conditionalPanel("input.Dist=='Chi-Square' | input.Dist=='Student t' | input.Dist=='Exponential'", numericInput("v", label = "Enter the Degrees of Freedom(d.f)", value = 0, step = 1, min = 0, max = Inf))

conditionalPanel("input.Dist=='Uniform'", numericInput("a", label = "Enter the value of a", value = 0, step = 0.1, min = -Inf, max = Inf), numericInput("b", label = "Enter the value of b", value = 1, step = 0.1, min = 0, max = Inf))

selectInput("Out",label = "Select the Output", choices = c("PDF", "CDF","Quantile",""), selected = "")

conditionalPanel("input.Out=='PDF'", selectInput("ProbType", label = c("Probability Type"), choices = c("Equal to", "Less Than or Equal to", "Greater Than or Equal to", "Between Values(Inclusive)", "Extreme Values"),selected = "Equal to"))

conditionalPanel("input.Out=='PDF' & input.ProbType=='Equal to' | input.Out=='PDF' & input.ProbType=='Less Than or Equal to' | input.Out=='PDF' & input.ProbType=='Greater Than or Equal to'", numericInput("Value",label = withMathJax('Enter a Discrete value (\\(x\\)):'), 0))

conditionalPanel("input.Out=='PDF' & input.ProbType=='Between Values(Inclusive)' | input.Out=='PDF' & input.ProbType=='Extreme Values'", numericInput("Value1",label = withMathJax('Enter a Discrete value (\\(x_1\\)):'), 0), numericInput("Value2",label = withMathJax('Enter a Discrete value (\\(x_2\\)):'), 1))

conditionalPanel("input.Out=='CDF'", numericInput("CValue",label = withMathJax('Enter a Discrete value (\\(x\\)):'), 0))

conditionalPanel("input.Out=='Quantile'", numericInput("QValue",label = withMathJax('Enter a Percentile value(between 0 and 1):'), 0.5, step = 0.1))

```

Row 
-------------------------------------

### Plot

```{r}
#Normal

source("PDF.R")
source("CDF.R")

conditionalPanel("input.CDist=='Normal' & input.Out=='PDF' & input.ProbType=='Equal to'", renderPlot({normal_prob_area_plot(lb = input$Value-0.005,ub = input$Value+0.005, input$Mu, sqrt(as.numeric(input$Sigma)))}, height = 600, width = 1000))

conditionalPanel("input.CDist=='Normal' & input.Out=='PDF' & input.ProbType=='Less Than or Equal to'", renderPlot({normal_prob_area_plot(-Inf,ub = input$Value, input$Mu, sqrt(as.numeric(input$Sigma)))}, height = 600, width = 1000))

conditionalPanel("input.CDist=='Normal' & input.Out=='PDF' & input.ProbType=='Greater Than or Equal to'", renderPlot({normal_prob_area_plot(lb = input$Value,Inf, input$Mu, sqrt(as.numeric(input$Sigma)))}, height = 600, width = 1000))

conditionalPanel("input.CDist=='Normal' & input.Out=='PDF' & input.ProbType=='Between Values(Inclusive)'", renderPlot({normal_prob_area_plot(lb = input$Value1,ub = input$Value2, input$Mu, sqrt(as.numeric(input$Sigma)))}, height = 600, width = 1000))

conditionalPanel("input.CDist=='Normal' & input.Out=='PDF' & input.ProbType=='Extreme Values'", renderPlot({normal_prob_area_plot(lb = input$Value1,ub = input$Value2, input$Mu, sqrt(as.numeric(input$Sigma)), extreme = TRUE)}, height = 600, width = 1000))

conditionalPanel("input.CDist=='Normal' & input.Out=='CDF'", renderPlot({normal_prob_CDF_plot(lb = -Inf, ub = input$CValue, input$Mu, sqrt(as.numeric(input$Sigma)))}, height = 600, width = 1000))

conditionalPanel("input.CDist=='Normal' & input.Out=='Quantile'", renderPlot({normal_prob_area_plot(lb = -Inf, ub = qnorm(as.numeric(input$QValue), mean = input$Mu,sd = sqrt(as.numeric(input$Sigma))), input$Mu, sqrt(as.numeric(input$Sigma)))}, height = 600, width = 1000))

```   

### Formula {data-width=250}

```{r}
source("Formulas.R")

renderUI({
  if (input$Type=="Discrete") {
    switch (input$Dist,
      "Bernoulli" = BernForm,
      "Discrete Uniform" = DiscUnifForm,
      "Binomial" = BinForm,
      "Negative Binomial" = NegBinForm,
      "Poisson" = PoiForm,
      "Geometric" = GeomForm,
      "Hyper-Geometric" = HyperGeomForm
    )
    
  }else if (input$Type=="Continuous"){
    switch (input$Dist,
      "Normal" = NormForm,
      "Chi-Square" = ChiForm,
      "F" = FForm,
      "Student t" = TForm,
      "Gamma" = GamForm,
      "Exponential" = ExpForm,
      "Beta" = BetaForm,
      "Uniform" = ContUnifForm
    )
  } else {
    return()
  }
})
```

Row {data-height=100}
-------------------------------------

### Output {data-width=740}
  
```{r}

renderUI({
  if(input$Out=="PDF" & input$Probtype=="Equal to"){
    switch (input$Dist,
      "Normal" = 
    )
  } else if(input$Out=="PDF" & input$Probtype=="Less Than or Equal to"){
    
  } else if(input$Out=="PDF" & input$Probtype=="Greater Than or Equal to"){
    
  } else if(input$Out=="PDF" & input$Probtype=="Between Values(Inclusive)"){
    
  } else if(input$Out=="PDF" & input$Probtype=="Extreme Values"){
    
  } 
})



conditionalPanel("input.CDist=='Normal' & input.Out=='PDF' & input.ProbType=='Equal to'", renderUI({withMathJax(sprintf("$$\\mathbb{P}(X =  %.03f ) = 0 \\\\ f(X =  %.03f ) = %.04f$$",input$Value,input$Value,dnorm(as.numeric(input$Value), mean = as.numeric(input$Mu), sd = sqrt(as.numeric(input$Sigma)))))}))

conditionalPanel("input.CDist=='Normal' & input.Out=='PDF' & input.ProbType=='Less Than or Equal to'", renderUI({withMathJax(sprintf("The probability that \\(X\\) is Less than or equal to %.03f is $$\\int_{-\\infty}^{%.03f} f(x) \\, dx \\approx %.04f$$",input$Value,input$Value,pnorm(as.numeric(input$Value), mean = as.numeric(input$Mu), sd = sqrt(as.numeric(input$Sigma)))))}))

conditionalPanel("input.CDist=='Normal' & input.Out=='PDF' & input.ProbType=='Greater Than or Equal to'", renderUI({withMathJax(sprintf("The probability that \\(X\\) is Greater than or equal to %.03f is $$1-\\int_{-\\infty}^{%.03f} f(x) \\, dx \\approx %.04f$$",input$Value,input$Value,1-pnorm(as.numeric(input$Value), mean = as.numeric(input$Mu), sd = sqrt(as.numeric(input$Sigma)))))}))

conditionalPanel("input.CDist=='Normal' & input.Out=='PDF' & input.ProbType=='Between Values(Inclusive)'", renderUI({withMathJax(sprintf("The probability that \\(X\\) is between %.03f and %.03f (inclusive) is $$\\int\\limits_{%.03f}^{%.03f} f(x) \\, dx = \\mathbb{P}(X \\leq %.04f) - \\mathbb{P}(X \\leq %.04f) \\approx %.04f$$",input$Value1,input$Value2,input$Value1,input$Value2,input$Value2,input$Value1,pnorm(as.numeric(input$Value2), mean = as.numeric(input$Mu), sd = sqrt(as.numeric(input$Sigma))) - pnorm(as.numeric(input$Value1), mean = as.numeric(input$Mu), sd = sqrt(as.numeric(input$Sigma)))))}))

conditionalPanel("input.CDist=='Normal' & input.Out=='PDF' & input.ProbType=='Extreme Values'", renderUI({withMathJax(sprintf("The probability that \\(X\\) is less than or equal to %.03f or greater than or equal to %.03f is $$\\int\\limits_{\\large{x \\, \\leq \\, %.03f}} f(x) \\, dx + \\int\\limits_{\\large{x \\, \\geq \\, %.03f}} f(x) \\, dx = \\mathbb{P}(X \\leq %.03f) + \\mathbb{P}(X \\geq %.03f) \\approx %.04f$$",input$Value1,input$Value2,input$Value1,input$Value2,input$Value1,input$Value2,1 - pnorm(as.numeric(input$Value2), as.numeric(input$Mu), sqrt(as.numeric(input$Sigma))) + pnorm(as.numeric(input$Value1), as.numeric(input$Mu), sqrt(as.numeric(input$Sigma)))))}))

conditionalPanel("input.CDist=='Normal' & input.Out=='CDF'", renderUI({withMathJax(sprintf("$$F(%.03f) = \\mathbb{P}(X \\leq  %.03f ) = %.04f$$",input$CValue,input$CValue,pnorm(as.numeric(input$CValue), 
                                                 mean = as.numeric(input$Mu),
                                                 sd = sqrt(as.numeric(input$Sigma)))))}))

conditionalPanel("input.CDist=='Normal' & input.Out=='Quantile'", renderUI({withMathJax(sprintf("\\(\\mathbb{P}(X \\le x) = \\) %.03f corresponds to an \\(x\\) value of %.04f \\( = F^{-1}(%.03f).\\)",input$QValue,qnorm(as.numeric(input$QValue), mean = input$Mu,sd = sqrt(as.numeric(input$Sigma))),input$QValue))}))

```

### Mean 
```{r}

renderUI({
  if (input$Type == "Discrete") {
    switch (input$Dist,
      "Discrete Uniform" = withMathJax(sprintf("$$\\mathbb{E}(X) = \\frac{a+b}{2} = \\frac{%.03f + %.03f}{2} = %.04f$$", input$a, input$b, (input$a + input$b)/2)),
      "Bernoulli" = withMathJax(sprintf("$$\\mathbb{E}(X) = p = %.04f$$", input$p)),
      "Binomial" = withMathJax(sprintf("$$\\mathbb{E}(X) = np = (%.03f) (%.03f) = %.04f$$",                     input$n, input$p, (input$n * input$p))),
      "Negative Binomial" = withMathJax(sprintf("$$\\mathbb{E}(X) = \\frac{r}{p} = \\frac{%d}{%0.3f} =          %.04f$$",input$n,input$p,(input$n / input$p))),
      "Poisson" = withMathJax(sprintf("$$\\mathbb{E}(X) = \\lambda = %.04f$$", input$lambda)),
      "Geometric" = withMathJax(sprintf("$$\\mathbb{E}(X) = \\frac{1}{p} = \\frac{1}{%.03f} =                   %.04f$$",input$p,(1 / input$p))),
      "Hyper-Geometric" = withMathJax(sprintf("$$\\mathbb{E}(X) = \\frac{nm}{N} = \\frac{%d \\cdot              %d}{%d} = %.04f$$",input$N,input$n,input$m,(input$N * input$n /input$m)))
    )
  } else if (input$Type == "Continuous"){
    switch (input$Dist,
      "Normal" = withMathJax(sprintf("$$\\mathbb{E}(X) = \\mu = %.02f$$",input$Mu)),
      "Chi-Square" = withMathJax(sprintf("$$\\mathbb{E}(X) = \\nu = %.04f$$",input$v)),
      "F" = withMathJax(sprintf("$$\\mathbb{E}(X) = \\frac{d_2}{d_2 - 2} =                \\frac{%.03f}{%.03f - 2} = %.04f$$",input$d2,input$d2,input$d2/(input$d2 - 2))),
      "Student t" = withMathJax(sprintf("$$\\mathbb{E}(X) = 0$$")),
      "Gamma" = withMathJax(sprintf("$$\\mathbb{E}(X) = \\alpha \\beta = %.03f \\cdot %.03f  =  %.04f$$",        input$d1,input$d2,(input$d1 * input$d2))),
      "Exponential" = withMathJax(sprintf("$$\\mathbb{E}(X) = \\beta = %.04f$$",input$v)),
      "Beta" = withMathJax(sprintf("$$\\mathbb{E}(X) = \\frac{\\alpha}{\\alpha + \\beta} =                      \\frac{%.03f}{%.03f + %.03f} = %.04f$$",input$d1,input$d1,input$d2,input$d1/(input$d1 + input$d2))),
      "Uniform" = withMathJax(sprintf("$$\\mathbb{E}(X) = \\frac{\\theta_1+\\theta_2}{2} = \\frac{%.03f +        %.03f}{2} = %.04f$$",input$a,input$b,(input$a + input$b)/2))
    )
  }
})

``` 

### Variance

```{r}

renderUI({
  if (input$Type == "Discrete") {
    switch (input$Dist,
      "Discrete Uniform" = withMathJax(sprintf("Variance is $$\\mathbb{V}(X) = \\frac{(b - a +1)^2 - 1}{12} =           \\frac{(%.03f - %.03f + 1)^2 - 1}{12} = %.04f$$",input$b,input$a,((input$b - input$a + 1)^2 -1)/12)),
      "Bernoulli" = withMathJax(sprintf("Variance is $$\\mathbb{V}(X) = p(1-p) = (%.03f)(1-%.03f) = %.04f$$",           input$p,input$p,(input$p*(1-input$p)))),
      "Binomial" = withMathJax(sprintf("Variance is $$\\mathbb{V}(X) = np(1-p) = (%d)(%.03f)(1-%.03f) = %.04f$$",        input$n,input$p,input$p,(input$n * input$p * (1-input$p)))),
      "Negative Binomial" = withMathJax(sprintf("Variance is $$\\mathbb{V}(X) = \\frac{r(1-p)}{p^2} = \\frac{%d(1-%.03f)}{(%.03f)^2} = %.04f$$",
                                          input$n,
                                          input$p,
                                          input$p,
                                          ( (input$n * (1-input$p) ) / ( (input$p)^2 ) )
             )),
      "Poisson" = withMathJax(sprintf("Variance is $$\\mathbb{V}(X) = \\lambda = %.04f$$",
                                         input$lambda
             )),
      "Geometric" = withMathJax(sprintf("Variance is $$\\mathbb{V}(X) = \\frac{1-p}{p^2} =                              \\frac{1-%.03f}{(%.03f)^2} = %.04f$$",input$p,input$p,((1-input$p) / (input$p)^2))),
      "Hyper-Geometric" = withMathJax(sprintf("Variance is $$\\mathbb{V}(X) =                                           \\frac{N-n}{N-1}\\left(\\frac{nm}{N}\\right)\\left( 1-\\frac{m}{N} \\right) =                                    \\frac{%d-%d}{%d-1}\\left(\\frac{%d \\cdot %d}{%d}\\right)\\left( 1-\\frac{%d}{%d} \\right)  =                   %.04f$$",input$numEvents,input$numTrials,input$numEvents,input$numTrials,input$favBalls,input$numEvents,input$favBalls,input$numEvents,((input$numEvents - input$numTrials)/(input$numEvents-1)) *((input$numTrials *input$favBalls)/(input$numEvents))*(1- input$favBalls/(input$numEvents))))
    )
  } else if (input$Type == "Continuous") {
    switch (input$Dist,
             "Beta" = withMathJax(sprintf("Variance is $$\\mathbb{V}(X) = \\frac{\\alpha + \\beta}{(\\alpha + \\beta)^2(\\alpha + \\beta + 1)} 
                                          = \\frac{%.03f + %.03f}{(%.03f + %.03f)^2(%.03f + %.03f + 1)} = %.04f$$",
                                          input$d1,
                                          input$d2,
                                          input$d1,
                                          input$d2,
                                          input$d1,
                                          input$d2,
                                          (input$d1 + input$d2)/((input$d1 + input$d2)^2 * (input$d1 + input$d2 + 1))
             )),
             
             "Chi-Square" = withMathJax(sprintf("Variance is $$\\mathbb{V}(X) = 2\\nu = 2 * %.03f = %.04f$$",
                                           input$v,
                                           2 * input$v
             )), 
             
             "Exponential" = withMathJax(sprintf("Variance is $$\\mathbb{V}(X) = \\beta^2 = %.04f$$",
                                         input$v^2
             )),
             
             "F" = withMathJax(sprintf("Variance (for \\( d_2 > 4\\) ) is $$\\mathbb{V}(X) = \\frac{2 {d_2}^2 (d_1 + d_2 - 2)}{d_1 (d_2 - 2)^2 (d_2 - 4)}
                                       = \\frac{2 * %.02f^2 (%.02f + %.02f - 2)}{%.02f (%.02f - 2)^2 (%.02f - 4)} = %.04f$$",
                                       input$d2,
                                       input$d1,
                                       input$d2,
                                       input$d1,
                                       input$d2,
                                       input$d2,
                                       (2 * input$d2^2  * (input$d1 + input$d2 - 2))/(input$d1 * (input$d2 - 2)^2 * (input$d2 - 4))
             )),
             
             "Gamma" = withMathJax(sprintf("Variance is $$\\mathbb{V}(X) = \\alpha \\beta^2 = %d (%d)^2  =  %.04f$$",
                                         input$d1,
                                         input$d2,
                                         (input$d1 * input$d2^2)
             )),
             
             "Normal" = withMathJax(sprintf("Variance is $$\\mathbb{V}(X) = \\sigma^2 = %.04f$$",
                                          input$Sigma
             )), 
             
             "Student t" = withMathJax(sprintf("Variance (for \\( \\nu > 2\\) ) is $$\\mathbb{V}(X) = \\frac{\\nu}{\\nu - 2} = \\frac{%.03f}{%.03f - 2} = %.04f$$",
                                       input$v,
                                       input$v,
                                       input$v/(input$v-2)
             )), 
             
             "Uniform" = withMathJax(sprintf("Variance is $$\\mathbb{V}(X) = \\frac{(\\theta_2-\\theta_1)^2}{12} = \\frac{(%d - %d)^2}{12} = %.04f$$",
                                          input$b,
                                          input$a,
                                          (input$b - input$a)^2 /12
             )),
    )
  }
})

```

Visualizing Central Limit Theorem
=====================================     

Sidebar {.sidebar}
-------------------------------------

#### Distribution Parameters

```{r}
selectInput("T", label = "Select the Distribution Type",
            choices = c("Discrete", "Continuous",""), selected = "")

conditionalPanel("input.T=='Discrete'",selectInput("DD", label = "Select the Distribution", choices = c("Discrete Uniform","Bernoulli","Binomial","Negative Binomial","Poisson","Geometric", "Hyper-Geometric",""), selected = ""))

conditionalPanel("input.T=='Continuous'",selectInput("CD",label = "Select the Distribution", choices = c("Normal","Chi-Square","F","Student t","Gamma","Exponential","Beta","Uniform",""), selected = ""))

```


Row 
-------------------------------------

### Chart 1
    
```{r}
```